### ISSUE TITLE
Ephemeral key should be "Symmetric key agreement key"

### ISSUE THREAD

**Issue by jimmykane** [paragonie/EasyRSA#3]
Hi there guys, 

Lately we started using your library for some convenience methods for storing encrypted data. 
Great work! 

To the point. In the encrypt/decrypt [method](https://github.com/paragonie/EasyRSA/blob/master/src/EasyRSA.php#L48) you name the generated key as ephemeral which is incorrect according to key cryptography, as far as I know, and should be named: "Symmetric key agreement key" according to [wiki](https://en.wikipedia.org/wiki/Cryptographic_key_types)

**Comment by paragonie-scott** [comment]
We're not doing Diffie Hellman there. This is the process the library follows.
1. Generate random AES key.
2. Encrypt message using [Defuse Security's library](https://github.com/defuse/php-encryption)
3. Encrypt the AES key with the RSA public key.
4. Store both ciphertexts into a string.

**Comment by jimmykane** [comment]
Thanks. Clear enough.
